
import { Lesson, DifficultyLevel, ConversationScenario, Vocabulary, LessonContent } from './types';

export const ALPHABET_DATA: LessonContent[] = [
  { id: 'a', letter: 'A', italian: 'Arancia', bangla: 'কমলা', exampleWord: 'Arancia' },
  { id: 'b', letter: 'B', italian: 'Barca', bangla: 'নৌকা', exampleWord: 'Barca' },
  { id: 'c', letter: 'C', italian: 'Cane', bangla: 'কুকুর', exampleWord: 'Cane' },
  { id: 'd', letter: 'D', italian: 'Dado', bangla: 'লুডুর ছক্কা', exampleWord: 'Dado' },
  { id: 'e', letter: 'E', italian: 'Elefante', bangla: 'হাতি', exampleWord: 'Elefante' },
  { id: 'f', letter: 'F', italian: 'Fiore', bangla: 'ফুল', exampleWord: 'Fiore' },
  { id: 'g', letter: 'G', italian: 'Gatto', bangla: 'বিড়াল', exampleWord: 'Gatto' },
  { id: 'h', letter: 'H', italian: 'Hotel', bangla: 'হোটেল', exampleWord: 'Hotel' },
  { id: 'i', letter: 'I', italian: 'Isola', bangla: 'দ্বীপ', exampleWord: 'Isola' },
  { id: 'j', letter: 'J', italian: 'Jeans', bangla: 'জিন্স', exampleWord: 'Jeans' },
  { id: 'k', letter: 'K', italian: 'Koala', bangla: 'কোয়ালা', exampleWord: 'Koala' },
  { id: 'l', letter: 'L', italian: 'Leone', bangla: 'সিংহ', exampleWord: 'Leone' },
  { id: 'm', letter: 'M', italian: 'Mela', bangla: 'আপেল', exampleWord: 'Mela' },
  { id: 'n', letter: 'N', italian: 'Nave', bangla: 'জাহাজ', exampleWord: 'Nave' },
  { id: 'o', letter: 'O', italian: 'Orso', bangla: 'ভল্লুক', exampleWord: 'Orso' },
  { id: 'p', letter: 'P', italian: 'Pane', bangla: 'পাউরুটি', exampleWord: 'Pane' },
  { id: 'q', letter: 'Q', italian: 'Quadro', bangla: 'ছবি', exampleWord: 'Quadro' },
  { id: 'r', letter: 'R', italian: 'Rana', bangla: 'ব্যাঙ', exampleWord: 'Rana' },
  { id: 's', letter: 'S', italian: 'Sole', bangla: 'সূর্য', exampleWord: 'Sole' },
  { id: 't', letter: 'T', italian: 'Treno', bangla: 'ট্রেন', exampleWord: 'Treno' },
  { id: 'u', letter: 'U', italian: 'Uccello', bangla: 'পাখি', exampleWord: 'Uccello' },
  { id: 'v', letter: 'V', italian: 'Vaso', bangla: 'ফুলদানি', exampleWord: 'Vaso' },
  { id: 'w', letter: 'W', italian: 'Wurstel', bangla: 'সসেজ', exampleWord: 'Wurstel' },
  { id: 'x', letter: 'X', italian: 'Xilofono', bangla: 'জাইলোফোন', exampleWord: 'Xilofono' },
  { id: 'y', letter: 'Y', italian: 'Yogurt', bangla: 'দই', exampleWord: 'Yogurt' },
  { id: 'z', letter: 'Z', italian: 'Zebra', bangla: 'জেব্রা', exampleWord: 'Zebra' },
];

export const GREETINGS_100: LessonContent[] = [
  { id: 'g1', italian: 'Buongiorno', bangla: 'শুভ সকাল' },
  { id: 'g2', italian: 'Buon pomeriggio', bangla: 'শুভ দুপুর' },
  { id: 'g3', italian: 'Buonasera', bangla: 'শুভ সন্ধ্যা' },
  { id: 'g4', italian: 'Buonanotte', bangla: 'শুভ রাত্রি' },
  { id: 'g5', italian: 'Ciao', bangla: 'হ্যালো / হাই' },
  { id: 'g6', italian: 'Salve', bangla: 'নমস্কার / অভিবাদন' },
  { id: 'g7', italian: 'Come stai?', bangla: 'কেমন আছো?' },
  { id: 'g8', italian: 'Come va?', bangla: 'কেমন চলছে?' },
  { id: 'g9', italian: 'Bene, grazie', bangla: 'ভালো, ধন্যবাদ' },
  { id: 'g10', italian: 'E tu?', bangla: 'আর তুমি?' },
  { id: 'g11', italian: 'Piacere di conoscerti', bangla: 'তোমার সাথে দেখা হয়ে ভালো লাগলো' },
  { id: 'g12', italian: 'Molto piacere', bangla: 'অনেক আনন্দিত' },
  { id: 'g13', italian: 'A presto', bangla: ' শীঘ্রই দেখা হবে' },
  { id: 'g14', italian: 'A dopo', bangla: 'পরে দেখা হবে' },
  { id: 'g15', italian: 'A domani', bangla: 'আগামীকাল দেখা হবে' },
  { id: 'g16', italian: 'Addio', bangla: 'বিদায় (চিরতরে)' },
  { id: 'g17', italian: 'Arrivederci', bangla: 'আবার দেখা হবে / বিদায়' },
  { id: 'g18', italian: 'Per favore', bangla: 'দয়া করে' },
  { id: 'g19', italian: 'Grazie mille', bangla: 'অনেক ধন্যবাদ' },
  { id: 'g20', italian: 'Prego', bangla: 'আপনাকে স্বাগতম' },
  { id: 'g21', italian: 'Scusa', bangla: 'দুঃখিত / মাফ করবেন (informal)' },
  { id: 'g22', italian: 'Mi dispiace', bangla: 'আমি দুঃখিত' },
  { id: 'g23', italian: 'Nessun problema', bangla: 'কোনো সমস্যা নেই' },
  { id: 'g24', italian: 'Non importa', bangla: 'কিছু মনে করো না' },
  { id: 'g25', italian: 'Sì', bangla: 'হ্যাঁ' },
  { id: 'g26', italian: 'No', bangla: 'না' },
  { id: 'g27', italian: 'Forse', bangla: 'হয়তো' },
  { id: 'g28', italian: 'Non lo so', bangla: 'আমি জানি না' },
  { id: 'g29', italian: 'Capisco', bangla: 'আমি বুঝতে পারছি' },
  { id: 'g30', italian: 'Non capisco', bangla: 'আমি বুঝছি না' },
  { id: 'g31', italian: 'Come ti chiami?', bangla: 'তোমার নাম কি?' },
  { id: 'g32', italian: 'Mi chiamo...', bangla: 'আমার নাম...' },
  { id: 'g33', italian: 'Quanti anni hai?', bangla: 'তোমার বয়স কত?' },
  { id: 'g34', italian: 'Ho ... anni', bangla: 'আমার বয়স ... বছর' },
  { id: 'g35', italian: 'Di dove sei?', bangla: 'তুমি কোথায় থাকো?' },
  { id: 'g36', italian: 'Sono di...', bangla: 'আমি ... থেকে এসেছি' },
  { id: 'g37', italian: 'Che ore sono?', bangla: 'কয়টা বাজে?' },
  { id: 'g38', italian: 'Che succede?', bangla: 'কি হচ্ছে?' },
  { id: 'g39', italian: 'Buon compleanno', bangla: 'শুভ জন্মদিন' },
  { id: 'g40', italian: 'Buona fortuna', bangla: 'শুভকামনা' },
  { id: 'g41', italian: 'Congratulazioni', bangla: 'অভিনন্দন' },
  { id: 'g42', italian: 'Salute!', bangla: 'সুস্বাস্থ্য! (হাঁচি দিলে)' },
  { id: 'g43', italian: 'Benvenuto', bangla: 'স্বাগতম' },
  { id: 'g44', italian: 'Accomodati', bangla: 'ভিতরে এসো / আরাম করে বসো' },
  { id: 'g45', italian: 'Prendi pure', bangla: 'ইচ্ছামত নাও' },
  { id: 'g46', italian: 'Basta così', bangla: 'এইটুকুই যথেষ্ট' },
  { id: 'g47', italian: 'Ancora un po’', bangla: 'আরও একটু' },
  { id: 'g48', italian: 'Tutto bene', bangla: 'সব ঠিক আছে' },
  { id: 'g49', italian: 'Così così', bangla: 'মোটামুটি' },
  { id: 'g50', italian: 'Male', bangla: 'খারাপ' },
  { id: 'g51', italian: 'Molto bene', bangla: 'খুব ভালো' },
  { id: 'g52', italian: 'Certo', bangla: 'অবশ্যই' },
  { id: 'g53', italian: 'D’accordo', bangla: 'ঠিক আছে / একমত' },
  { id: 'g54', italian: 'Eccomi', bangla: 'আমি এখানে' },
  { id: 'g55', italian: 'Aiuto!', bangla: 'বাঁচাও! / সাহায্য করুন!' },
  { id: 'g56', italian: 'Aspetta', bangla: 'অপেক্ষা করো' },
  { id: 'g57', italian: 'Vieni qui', bangla: 'এখানে এসো' },
  { id: 'g58', italian: 'Guarda', bangla: 'দেখো' },
  { id: 'g59', italian: 'Ascolta', bangla: 'শোনো' },
  { id: 'g60', italian: 'Dimmi', bangla: 'আমাকে বলো' },
  { id: 'g61', italian: 'Chiedimi', bangla: 'আমাকে জিজ্ঞাসা করো' },
  { id: 'g62', italian: 'Cosa vuoi?', bangla: 'তুমি কি চাও?' },
  { id: 'g63', italian: 'Cosa fai?', bangla: 'তুমি কি করছো?' },
  { id: 'g64', italian: 'Perché?', bangla: 'কেন?' },
  { id: 'g65', italian: 'Quando?', bangla: 'কখন?' },
  { id: 'g66', italian: 'Dove?', bangla: 'কোথায়?' },
  { id: 'g67', italian: 'Come?', bangla: 'কিভাবে?' },
  { id: 'g68', italian: 'Chi?', bangla: 'কে?' },
  { id: 'g69', italian: 'Quanto?', bangla: 'কতটুকু?' },
  { id: 'g70', italian: 'Quale?', bangla: 'কোনটি?' },
  { id: 'g71', italian: 'Sempre', bangla: 'সব সময়' },
  { id: 'g72', italian: 'Mai', bangla: 'কখনো না' },
  { id: 'g73', italian: 'Spesso', bangla: 'প্রায়ই' },
  { id: 'g74', italian: 'Qualche volta', bangla: 'মাঝে মাঝে' },
  { id: 'g75', italian: 'Adesso', bangla: 'এখন' },
  { id: 'g76', italian: 'Dopo', bangla: 'পরে' },
  { id: 'g77', italian: 'Prima', bangla: 'আগে' },
  { id: 'g78', italian: 'Qui', bangla: 'এখানে' },
  { id: 'g79', italian: 'Lì', bangla: 'সেখানে' },
  { id: 'g80', italian: 'Ovunque', bangla: 'যেকোনো জায়গায়' },
  { id: 'g81', italian: 'Tutto', bangla: 'সবকিছু' },
  { id: 'g82', italian: 'Niente', bangla: 'কিছু না' },
  { id: 'g83', italian: 'Qualcuno', bangla: 'কেউ একজন' },
  { id: 'g84', italian: 'Nessuno', bangla: 'কেউ না' },
  { id: 'g85', italian: 'Qualcosa', bangla: 'কিছু একটা' },
  { id: 'g86', italian: 'Molto', bangla: 'অনেক' },
  { id: 'g87', italian: 'Poco', bangla: 'অল্প' },
  { id: 'g88', italian: 'Troppo', bangla: 'খুব বেশি' },
  { id: 'g89', italian: 'Abbastanza', bangla: 'যথেষ্ট' },
  { id: 'g90', italian: 'Vero', bangla: 'সত্য' },
  { id: 'g91', italian: 'Falso', bangla: 'মিথ্যা' },
  { id: 'g92', italian: 'Bello', bangla: 'সুন্দর' },
  { id: 'g93', italian: 'Brutto', bangla: 'কুৎসিত' },
  { id: 'g94', italian: 'Grande', bangla: 'বড়' },
  { id: 'g95', italian: 'Piccolo', bangla: 'ছোট' },
  { id: 'g96', italian: 'Nuovo', bangla: 'নতুন' },
  { id: 'g97', italian: 'Vecchio', bangla: 'পুরানো' },
  { id: 'g98', italian: 'Facile', bangla: 'সহজ' },
  { id: 'g99', italian: 'Difficile', bangla: 'কঠিন' },
  { id: 'g100', italian: 'Pronto', bangla: 'প্রস্তুত / হ্যালো (ফোনে)' },
];

export const VERBS_100: LessonContent[] = [
  { id: 'v1', italian: 'Essere', bangla: 'হওয়া' },
  { id: 'v2', italian: 'Avere', bangla: 'থাকা / আছে' },
  { id: 'v3', italian: 'Fare', bangla: 'করা' },
  { id: 'v4', italian: 'Dire', bangla: 'বলা' },
  { id: 'v5', italian: 'Andare', bangla: 'যাওয়া' },
  { id: 'v6', italian: 'Venire', bangla: 'আসা' },
  { id: 'v7', italian: 'Vedere', bangla: 'দেখা' },
  { id: 'v8', italian: 'Sentire', bangla: 'শোনা / অনুভব করা' },
  { id: 'v9', italian: 'Sapere', bangla: 'জানা' },
  { id: 'v10', italian: 'Volere', bangla: 'চাওয়া' },
  { id: 'v11', italian: 'Potere', bangla: 'পারা' },
  { id: 'v12', italian: 'Dovere', bangla: 'উচিত / করতে হবে' },
  { id: 'v13', italian: 'Mangiare', bangla: 'খাওয়া' },
  { id: 'v14', italian: 'Bere', bangla: 'পান করা' },
  { id: 'v15', italian: 'Dormire', bangla: 'ঘুমানো' },
  { id: 'v16', italian: 'Lavorare', bangla: 'কাজ করা' },
  { id: 'v17', italian: 'Studiare', bangla: 'পড়াশোনা করা' },
  { id: 'v18', italian: 'Scrivere', bangla: 'লেখা' },
  { id: 'v19', italian: 'Leggere', bangla: 'পড়া' },
  { id: 'v20', italian: 'Parlare', bangla: 'কথা বলা' },
  { id: 'v21', italian: 'Prendere', bangla: 'নেওয়া' },
  { id: 'v22', italian: 'Dare', bangla: 'দেওয়া' },
  { id: 'v23', italian: 'Mettere', bangla: 'রাখা' },
  { id: 'v24', italian: 'Chiamare', bangla: 'ডাকা / কল করা' },
  { id: 'v25', italian: 'Cercare', bangla: 'খোঁজা' },
  { id: 'v26', italian: 'Trovare', bangla: 'খুঁজে পাওয়া' },
  { id: 'v27', italian: 'Chiedere', bangla: 'জি জিজ্ঞাসা করা' },
  { id: 'v28', italian: 'Rispondere', bangla: 'উত্তর দেওয়া' },
  { id: 'v29', italian: 'Comprare', bangla: 'কেনা' },
  { id: 'v30', italian: 'Vendere', bangla: 'বিক্রি করা' },
  { id: 'v31', italian: 'Pagare', bangla: 'টাকা দেওয়া / পে করা' },
  { id: 'v32', italian: 'Aspettare', bangla: 'অপেক্ষা করা' },
  { id: 'v33', italian: 'Pensare', bangla: 'চিন্তা করা' },
  { id: 'v34', italian: 'Credere', bangla: 'বিশ্বাস করা' },
  { id: 'v35', italian: 'Capire', bangla: 'বুঝতে পারা' },
  { id: 'v36', italian: 'Ricordare', bangla: 'মনে রাখা' },
  { id: 'v37', italian: 'Dimenticare', bangla: 'ভুলে যাওয়া' },
  { id: 'v38', italian: 'Vivere', bangla: 'বাস করা / বেঁচে থাকা' },
  { id: 'v39', italian: 'Morire', bangla: 'মারা যাওয়া' },
  { id: 'v40', italian: 'Nascere', bangla: 'জন্মানো' },
  { id: 'v41', italian: 'Sentire', bangla: 'শোনা / বোধ করা' },
  { id: 'v42', italian: 'Guardare', bangla: 'তাকানো / দেখা' },
  { id: 'v43', italian: 'Ascoltare', bangla: 'শোনা (মনোযোগ দিয়ে)' },
  { id: 'v44', italian: 'Camminare', bangla: 'হাঁটা' },
  { id: 'v45', italian: 'Correre', bangla: 'দৌড়ানো' },
  { id: 'v46', italian: 'Guidare', bangla: 'চালানো (গাড়ি)' },
  { id: 'v47', italian: 'Viaggiare', bangla: 'ভ্রমণ করা' },
  { id: 'v48', italian: 'Partire', bangla: 'প্রস্থান করা' },
  { id: 'v49', italian: 'Arrivare', bangla: 'পৌঁছানো' },
  { id: 'v50', italian: 'Tornare', bangla: 'ফিরে আসা' },
  { id: 'v51', italian: 'Entrare', bangla: 'প্রবেশ করা' },
  { id: 'v52', italian: 'Uscire', bangla: 'বাইরে যাওয়া' },
  { id: 'v53', italian: 'Salire', bangla: 'উপরে ওঠা' },
  { id: 'v54', italian: 'Scendere', bangla: 'নিচে নামা' },
  { id: 'v55', italian: 'Cadere', bangla: 'পড়ে যাওয়া' },
  { id: 'v56', italian: 'Aprire', bangla: 'খোলা' },
  { id: 'v57', italian: 'Chiudere', bangla: 'বন্ধ করা' },
  { id: 'v58', italian: 'Ridere', bangla: 'হাসা' },
  { id: 'v59', italian: 'Piangere', bangla: 'কাঁদা' },
  { id: 'v60', italian: 'Giocare', bangla: 'খেলা করা' },
  { id: 'v61', italian: 'Cantare', bangla: 'গান গাওয়া' },
  { id: 'v62', italian: 'Ballare', bangla: 'নাচা' },
  { id: 'v63', italian: 'Suonare', bangla: 'বাজানো' },
  { id: 'v64', italian: 'Amare', bangla: 'ভালোবাসা' },
  { id: 'v65', italian: 'Odiare', bangla: 'ঘৃণা করা' },
  { id: 'v66', italian: 'Piacere', bangla: 'পছন্দ হওয়া' },
  { id: 'v67', italian: 'Aiutare', bangla: 'সাহায্য করা' },
  { id: 'v68', italian: 'Sperare', bangla: 'আশা করা' },
  { id: 'v69', italian: 'Sognare', bangla: 'স্বপ্ন দেখা' },
  { id: 'v70', italian: 'Cucinare', bangla: 'রান্না করা' },
  { id: 'v71', italian: 'Lavare', bangla: 'ধোয়া' },
  { id: 'v72', italian: 'Pulire', bangla: 'পরিষ্কার করা' },
  { id: 'v73', italian: 'Ordinare', bangla: 'অর্ডার দেওয়া' },
  { id: 'v74', italian: 'Scegliere', bangla: 'বেছে নেওয়া' },
  { id: 'v75', italian: 'Usare', bangla: 'ব্যবহার করা' },
  { id: 'v76', italian: 'Finire', bangla: 'শেষ করা' },
  { id: 'v77', italian: 'Iniziare', bangla: 'শুরু করা' },
  { id: 'v78', italian: 'Perdere', bangla: 'হারানো' },
  { id: 'v79', italian: 'Vincere', bangla: 'জেতা' },
  { id: 'v80', italian: 'Provare', bangla: 'চেষ্টা করা' },
  { id: 'v81', italian: 'Cercare', bangla: 'চেষ্টা করা / খোঁজা' },
  { id: 'v82', italian: 'Poter', bangla: 'সক্ষম হওয়া' },
  { id: 'v83', italian: 'Rimanere', bangla: 'থাকা (অবিচল)' },
  { id: 'v84', italian: 'Tenere', bangla: 'ধরে রাখা' },
  { id: 'v85', italian: 'Portare', bangla: 'বহন করা / আনা' },
  { id: 'v86', italian: 'Lasciare', bangla: 'ছেড়ে দেওয়া' },
  { id: 'v87', italian: 'Cambiare', bangla: 'পরিবর্তন করা' },
  { id: 'v88', italian: 'Costruire', bangla: 'তৈরি করা' },
  { id: 'v89', italian: 'Distruggere', bangla: 'ধ্বংস করা' },
  { id: 'v90', italian: 'Imparare', bangla: 'শেখা' },
  { id: 'v91', italian: 'Insegnare', bangla: 'শেখানো' },
  { id: 'v92', italian: 'Viaggiare', bangla: 'ভ্রমণ করা' },
  { id: 'v93', italian: 'Nuotare', bangla: 'সাঁতার কাটা' },
  { id: 'v94', italian: 'Volare', bangla: 'ওড়া' },
  { id: 'v95', italian: 'Saltare', bangla: 'লাফানো' },
  { id: 'v96', italian: 'Baciare', bangla: 'চুমু দেওয়া' },
  { id: 'v97', italian: 'Abbracciare', bangla: 'কোলাকুলি করা' },
  { id: 'v98', italian: 'Sorridere', bangla: 'হাসি দেওয়া' },
  { id: 'v99', italian: 'Passeggiare', bangla: 'ভ্রমণ করা / হাঁটা' },
  { id: 'v100', italian: 'Smettere', bangla: 'থামা' },
];

export const INITIAL_VOCABULARY: Vocabulary[] = [
  // Numbers
  { italian: 'Zero', bangla: 'শূন্য', category: 'Numbers' },
  { italian: 'Uno', bangla: 'এক', category: 'Numbers' },
  { italian: 'Due', bangla: 'দুই', category: 'Numbers' },
  { italian: 'Tre', bangla: 'তিন', category: 'Numbers' },
  { italian: 'Quattro', bangla: 'চার', category: 'Numbers' },
  { italian: 'Cinque', bangla: 'পাঁচ', category: 'Numbers' },
  { italian: 'Sei', bangla: 'ছয়', category: 'Numbers' },
  { italian: 'Sette', bangla: 'সাত', category: 'Numbers' },
  { italian: 'Otto', bangla: 'আট', category: 'Numbers' },
  { italian: 'Nove', bangla: 'নয়', category: 'Numbers' },
  { italian: 'Dieci', bangla: 'দশ', category: 'Numbers' },
  { italian: 'Undici', bangla: 'এগারো', category: 'Numbers' },
  { italian: 'Dodici', bangla: 'বারো', category: 'Numbers' },
  { italian: 'Tredici', bangla: 'তেরো', category: 'Numbers' },
  { italian: 'Quattordici', bangla: 'চৌদ্দ', category: 'Numbers' },
  { italian: 'Quindici', bangla: 'পনের', category: 'Numbers' },
  { italian: 'Sedici', bangla: 'ষোল', category: 'Numbers' },
  { italian: 'Diciassette', bangla: 'সতের', category: 'Numbers' },
  { italian: 'Diciotto', bangla: 'আঠার', category: 'Numbers' },
  { italian: 'Diciannove', bangla: 'উনিশ', category: 'Numbers' },
  { italian: 'Venti', bangla: 'বিশ', category: 'Numbers' },
  { italian: 'Trenta', bangla: 'ত্রিশ', category: 'Numbers' },
  { italian: 'Quaranta', bangla: 'চল্লিশ', category: 'Numbers' },
  { italian: 'Cinquanta', bangla: 'পঞ্চাশ', category: 'Numbers' },
  { italian: 'Sessanta', bangla: 'ষাট', category: 'Numbers' },
  { italian: 'Settanta', bangla: 'সত্তর', category: 'Numbers' },
  { italian: 'Ottanta', bangla: 'আশি', category: 'Numbers' },
  { italian: 'Novanta', bangla: 'নব্বই', category: 'Numbers' },
  { italian: 'Cento', bangla: 'একশ', category: 'Numbers' },
  { italian: 'Mille', bangla: 'এক হাজার', category: 'Numbers' },
  { italian: 'Un Milione', bangla: 'দশ লক্ষ (এক মিলিয়ন)', category: 'Numbers' },

  // Ordinals
  { italian: 'Primo', bangla: 'প্রথম', category: 'Ordinals' },
  { italian: 'Secondo', bangla: 'দ্বিতীয়', category: 'Ordinals' },
  { italian: 'Terzo', bangla: 'তৃতীয়', category: 'Ordinals' },
  { italian: 'Quarto', bangla: 'চতুর্থ', category: 'Ordinals' },
  { italian: 'Quinto', bangla: 'পঞ্চম', category: 'Ordinals' },
  { italian: 'Sesto', bangla: 'ষষ্ঠ', category: 'Ordinals' },
  { italian: 'Settimo', bangla: 'সপ্তম', category: 'Ordinals' },
  { italian: 'Ottavo', bangla: 'অষ্টম', category: 'Ordinals' },
  { italian: 'Nono', bangla: 'নবম', category: 'Ordinals' },
  { italian: 'Decimo', bangla: 'দশম', category: 'Ordinals' },

  // Weeks (7 items)
  { italian: 'Lunedì', bangla: 'সোমবার', category: 'Weeks' },
  { italian: 'Martedì', bangla: 'মঙ্গলবার', category: 'Weeks' },
  { italian: 'Mercoledì', bangla: 'বুধবার', category: 'Weeks' },
  { italian: 'Giovedì', bangla: 'বৃহস্পতিবার', category: 'Weeks' },
  { italian: 'Venerdì', bangla: 'শুক্রবার', category: 'Weeks' },
  { italian: 'Sabato', bangla: 'শনিবার', category: 'Weeks' },
  { italian: 'Domenica', bangla: 'রবিবার', category: 'Weeks' },

  // Months (12 items)
  { italian: 'Gennaio', bangla: 'জানুয়ারি', category: 'Months' },
  { italian: 'Febbraio', bangla: 'ফেব্রুয়ারি', category: 'Months' },
  { italian: 'Marzo', bangla: 'মার্চ', category: 'Months' },
  { italian: 'Aprile', bangla: 'এপ্রিল', category: 'Months' },
  { italian: 'Maggio', bangla: 'মে', category: 'Months' },
  { italian: 'Giugno', bangla: 'জুন', category: 'Months' },
  { italian: 'Luglio', bangla: 'জুলাই', category: 'Months' },
  { italian: 'Agosto', bangla: 'আগস্ট', category: 'Months' },
  { italian: 'Settembre', bangla: 'সেপ্টেম্বর', category: 'Months' },
  { italian: 'Ottobre', bangla: 'অক্টোবর', category: 'Months' },
  { italian: 'Novembre', bangla: 'নভেম্বর', category: 'Months' },
  { italian: 'Dicembre', bangla: 'ডিসেম্বর', category: 'Months' },

  // Seasons (4 items)
  { italian: 'Primavera', bangla: 'বসন্তকাল', category: 'Seasons' },
  { italian: 'Estate', bangla: 'গ্রীষ্মকাল', category: 'Seasons' },
  { italian: 'Autunno', bangla: 'শরৎকাল', category: 'Seasons' },
  { italian: 'Inverno', bangla: 'শীতকাল', category: 'Seasons' },

  // Vegetables
  { italian: 'Patata', bangla: 'আলু', category: 'Vegetables' },
  { italian: 'Cipolla', bangla: 'পেঁয়াজ', category: 'Vegetables' },
  { italian: 'Pomodoro', bangla: 'টমেটো', category: 'Vegetables' },
  { italian: 'Aglio', bangla: 'রসুন', category: 'Vegetables' },
  { italian: 'Carota', bangla: 'গাজর', category: 'Vegetables' },
  { italian: 'Melanzana', bangla: 'বেগুন', category: 'Vegetables' },
  { italian: 'Zucchina', bangla: 'ধুন্দুল', category: 'Vegetables' },
  { italian: 'Cetriolo', bangla: 'শসা', category: 'Vegetables' },
  { italian: 'Peperoncino', bangla: 'কাঁচামরিচ', category: 'Vegetables' },
  { italian: 'Peperone', bangla: 'ক্যাপসিকাম', category: 'Vegetables' },
  { italian: 'Spinaci', bangla: 'পালং শাক', category: 'Vegetables' },
  { italian: 'Lattuga', bangla: 'লেটুস পাতা', category: 'Vegetables' },
  { italian: 'Cavolo', bangla: 'বাঁধাকপি', category: 'Vegetables' },
  { italian: 'Cavolfiore', bangla: 'ফুলকপি', category: 'Vegetables' },
  { italian: 'Broccolo', bangla: 'ব্রকলি', category: 'Vegetables' },
  { italian: 'Fagioli', bangla: 'সীম', category: 'Vegetables' },
  { italian: 'Piselli', bangla: 'মটরশুটি', category: 'Vegetables' },
  { italian: 'Zucca', bangla: 'মিষ্টি কুমড়া', category: 'Vegetables' },
  { italian: 'Zenzero', bangla: 'আদা', category: 'Vegetables' },
  { italian: 'Radice', bangla: 'মূল', category: 'Vegetables' },
  { italian: 'Rapa', bangla: 'শালগম', category: 'Vegetables' },
  { italian: 'Sedano', bangla: 'সেলারি', category: 'Vegetables' },
  { italian: 'Prezzemolo', bangla: 'পার্সলে', category: 'Vegetables' },
  { italian: 'Basilico', bangla: 'তুলসী পাতা', category: 'Vegetables' },
  { italian: 'Mais', bangla: 'ভুট্টা', category: 'Vegetables' },
  { italian: 'Asparago', bangla: 'অ্যাসপারাগাস', category: 'Vegetables' },
  { italian: 'Carciofo', bangla: 'আর্টিচোক', category: 'Vegetables' },
  { italian: 'Porro', bangla: 'লিক', category: 'Vegetables' },
  { italian: 'Funghi', bangla: 'মাশরুম', category: 'Vegetables' },
  { italian: 'Olive', bangla: 'জলপাই', category: 'Vegetables' },

  // Fruits
  { italian: 'Mela', bangla: 'আপেল', category: 'Fruits' },
  { italian: 'Banana', bangla: 'কলা', category: 'Fruits' },
  { italian: 'Arancia', bangla: 'কমলা', category: 'Fruits' },
  { italian: 'Uva', bangla: 'আঙুর', category: 'Fruits' },
  { italian: 'Mango', bangla: 'আম', category: 'Fruits' },
  { italian: 'Limone', bangla: 'লেবু', category: 'Fruits' },
  { italian: 'Anguria', bangla: 'তরমুজ', category: 'Fruits' },
  { italian: 'Fragola', bangla: 'স্ট্রবেরি', category: 'Fruits' },
  { italian: 'Ananas', bangla: 'আনারস', category: 'Fruits' },
  { italian: 'Pera', bangla: 'নাশপাতি', category: 'Fruits' },
  { italian: 'Pesca', bangla: 'পিচ ফল', category: 'Fruits' },
  { italian: 'Ciliegia', bangla: 'চেরি ফল', category: 'Fruits' },
  { italian: 'Melone', bangla: 'ফুটি / বাঙ্গি', category: 'Fruits' },
  { italian: 'Prugna', bangla: 'আলুবোখারা', category: 'Fruits' },
  { italian: 'Albicocca', bangla: 'এপ্রিকট', category: 'Fruits' },
  { italian: 'Kiwi', bangla: 'কিউই ফল', category: 'Fruits' },
  { italian: 'Cocco', bangla: 'নারকেল', category: 'Fruits' },
  { italian: 'Papaya', bangla: 'পেঁপে', category: 'Fruits' },
  { italian: 'Litchi', bangla: 'লিচু', category: 'Fruits' },
  { italian: 'Melograno', bangla: 'ডালিম', category: 'Fruits' },
  { italian: 'Fico', bangla: 'ডুমুর', category: 'Fruits' },
  { italian: 'Dattero', bangla: 'খেজুর', category: 'Fruits' },
  { italian: 'Guava', bangla: 'পেয়ারা', category: 'Fruits' },
  { italian: 'Mora', bangla: 'ব্ল্যাকবেরি', category: 'Fruits' },
  { italian: 'Lampone', bangla: 'রাসবেরি', category: 'Fruits' },
  { italian: 'Mirtillo', bangla: 'ব্লুবেরি', category: 'Fruits' },
  { italian: 'Pompelmo', bangla: 'বাতাবি লেবু', category: 'Fruits' },
  { italian: 'Mandarino', bangla: 'ছোট কমলা', category: 'Fruits' },
  { italian: 'Avocado', bangla: 'অ্যাভোকাডো', category: 'Fruits' },
  { italian: 'Cachi', bangla: 'পার্সিমন', category: 'Fruits' },

  // Drinking
  { italian: 'Acqua', bangla: 'জল / পানি', category: 'Drinking' },
  { italian: 'Tè', bangla: 'চা', category: 'Drinking' },
  { italian: 'Caffè', bangla: 'কফি', category: 'Drinking' },
  { italian: 'Latte', bangla: 'দুধ', category: 'Drinking' },
  { italian: 'Succo', bangla: 'জুস', category: 'Drinking' },
  { italian: 'Vino', bangla: 'ওয়াইন', category: 'Drinking' },
  { italian: 'Birra', bangla: 'বিয়ার', category: 'Drinking' },
  { italian: 'Bibita', bangla: 'কোমল পানীয়', category: 'Drinking' },
  { italian: 'Limonata', bangla: 'লেবুর শরবত', category: 'Drinking' },
  { italian: 'Succo d\'arancia', bangla: 'কমলার রস', category: 'Drinking' },
  { italian: 'Succo di mela', bangla: 'আপেলের রস', category: 'Drinking' },
  { italian: 'Acqua gassata', bangla: 'গ্যাসীয় জল', category: 'Drinking' },
  { italian: 'Cioccolata calda', bangla: 'হট চকলেট', category: 'Drinking' },
  { italian: 'Frappé', bangla: 'মিল্কশেক', category: 'Drinking' },
  { italian: 'Cocktail', bangla: 'ককটেল', category: 'Drinking' },
  { italian: 'Spumante', bangla: 'শ্যাম্পেন', category: 'Drinking' },
  { italian: 'Tisana', bangla: 'ভেষজ চা', category: 'Drinking' },
  { italian: 'Caffelatte', bangla: 'দুধ কফি', category: 'Drinking' },
  { italian: 'Cappuccino', bangla: 'কাপুচিনো', category: 'Drinking' },
  { italian: 'Espresso', bangla: 'এসপ্রেসো', category: 'Drinking' },
  { italian: 'Tè freddo', bangla: 'ঠান্ডা চা', category: 'Drinking' },
  { italian: 'Succo di frutta', bangla: 'ফলের রস', category: 'Drinking' },
  { italian: 'Ghiaccio', bangla: 'বরফ', category: 'Drinking' },
  { italian: 'Tè verde', bangla: 'সবুজ চা', category: 'Drinking' },
  { italian: 'Centrifugato', bangla: 'স্মুদি', category: 'Drinking' },
  { italian: 'Acqua naturale', bangla: 'সাধারণ জল', category: 'Drinking' },
  { italian: 'Aperitivo', bangla: 'খাবার আগের পানীয়', category: 'Drinking' },
  { italian: 'Liquore', bangla: 'মদ', category: 'Drinking' },
  { italian: 'Spremuta', bangla: 'তাজা চিপানো রস', category: 'Drinking' },
  { italian: 'Bevanda energetica', bangla: 'এনার্জি ড্রিংক', category: 'Drinking' },

  // School
  { italian: 'Scuola', bangla: 'স্কুল', category: 'School' },
  { italian: 'Libro', bangla: 'বই', category: 'School' },
  { italian: 'Quaderno', bangla: 'খাতা', category: 'School' },
  { italian: 'Penna', bangla: 'কলম', category: 'School' },
  { italian: 'Matita', bangla: 'পেন্সিল', category: 'School' },
  { italian: 'Zaino', bangla: 'ব্যাগ', category: 'School' },
  { italian: 'Insegnante', bangla: 'শিক্ষক', category: 'School' },
  { italian: 'Studente', bangla: 'ছাত্র', category: 'School' },
  { italian: 'Aula', bangla: 'শ্রেণীকক্ষ', category: 'School' },
  { italian: 'Lavagna', bangla: 'ব্ল্যাকবোর্ড', category: 'School' },
  { italian: 'Banco', bangla: 'বেঞ্চ / ডেস্ক', category: 'School' },
  { italian: 'Sedia', bangla: 'চেয়ার', category: 'School' },
  { italian: 'Gomma', bangla: 'ইরেজার', category: 'School' },
  { italian: 'Righello', bangla: 'স্কেল', category: 'School' },
  { italian: 'Forbici', bangla: 'কাঁচি', category: 'School' },
  { italian: 'Colla', bangla: 'আঠা', category: 'School' },
  { italian: 'Mappa', bangla: 'মানচিত্র', category: 'School' },
  { italian: 'Compiti', bangla: 'বাড়ির কাজ', category: 'School' },
  { italian: 'Lezione', bangla: 'পাঠ / লেসন', category: 'School' },
  { italian: 'Esame', bangla: 'পরীক্ষা', category: 'School' },
  { italian: 'Voto', bangla: 'গ্রেড / নম্বর', category: 'School' },
  { italian: 'Biblioteca', bangla: 'লাইব্রেরি', category: 'School' },
  { italian: 'Laboratorio', bangla: 'ল্যাবরেটরি', category: 'School' },
  { italian: 'Matematica', bangla: 'গণিত', category: 'School' },
  { italian: 'Storia', bangla: 'ইতিহাস', category: 'School' },
  { italian: 'Scienze', bangla: 'বিজ্ঞান', category: 'School' },
  { italian: 'Lingua', bangla: 'ভাষা', category: 'School' },
  { italian: 'Dizionario', bangla: 'অভিধান', category: 'School' },
  { italian: 'Computer', bangla: 'কম্পিউটার', category: 'School' },
  { italian: 'Astuccio', bangla: 'পেন্সিল বক্স', category: 'School' },

  // Body Parts
  { italian: 'Testa', bangla: 'মাথা', category: 'Body Parts' },
  { italian: 'Capelli', bangla: 'চুল', category: 'Body Parts' },
  { italian: 'Faccia', bangla: 'মুখমণ্ডল', category: 'Body Parts' },
  { italian: 'Occhio', bangla: 'চোখ', category: 'Body Parts' },
  { italian: 'Orecchio', bangla: 'কান', category: 'Body Parts' },
  { italian: 'Naso', bangla: 'নাক', category: 'Body Parts' },
  { italian: 'Bocca', bangla: 'মুখ', category: 'Body Parts' },
  { italian: 'Labbra', bangla: 'ঠোঁট', category: 'Body Parts' },
  { italian: 'Dente', bangla: 'দাঁত', category: 'Body Parts' },
  { italian: 'Lingua', bangla: 'জিহ্বা', category: 'Body Parts' },
  { italian: 'Gola', bangla: 'গলা', category: 'Body Parts' },
  { italian: 'Collo', bangla: 'ঘাড়', category: 'Body Parts' },
  { italian: 'Spalla', bangla: 'কাঁধ', category: 'Body Parts' },
  { italian: 'Braccio', bangla: 'হাত', category: 'Body Parts' },
  { italian: 'Gomito', bangla: 'কনুই', category: 'Body Parts' },
  { italian: 'Mano', bangla: 'হাত (কবজি)', category: 'Body Parts' },
  { italian: 'Dito', bangla: 'আঙুল', category: 'Body Parts' },
  { italian: 'Unghia', bangla: 'নখ', category: 'Body Parts' },
  { italian: 'Petto', bangla: 'বুক', category: 'Body Parts' },
  { italian: 'Cuore', bangla: 'হৃদয়', category: 'Body Parts' },
  { italian: 'Pancia', bangla: 'পেট', category: 'Body Parts' },
  { italian: 'Schiena', bangla: 'পিঠ', category: 'Body Parts' },
  { italian: 'Gamba', bangla: 'পা', category: 'Body Parts' },
  { italian: 'Ginocchio', bangla: 'হাঁটু', category: 'Body Parts' },
  { italian: 'Piede', bangla: 'পায়ের পাতা', category: 'Body Parts' },
  { italian: 'Caviglia', bangla: 'গোড়ালি', category: 'Body Parts' },
  { italian: 'Pelle', bangla: 'ত্বক', category: 'Body Parts' },
  { italian: 'Sangue', bangla: 'রক্ত', category: 'Body Parts' },
  { italian: 'Osso', bangla: 'হাড়', category: 'Body Parts' },
  { italian: 'Muscolo', bangla: 'পেশি', category: 'Body Parts' },
];

export const CONVERSATIONS: ConversationScenario[] = [
  {
    id: 'c1',
    title: 'Al Bar',
    banglaTitle: 'বারে বা ক্যাফেতে',
    icon: '☕',
    dialogue: [
      { speaker: 'Marco', italian: 'Buongiorno!', bangla: 'শুভ সকাল!' },
      { speaker: 'Barista', italian: 'Buongiorno, desidera?', bangla: 'শুভ সকাল, কী চান?' },
      { speaker: 'Marco', italian: 'Un caffè e un cornetto, per favore.', bangla: 'একটি কফি এবং একটি করনেত্তো দিন, দয়া করে।' },
      { speaker: 'Barista', italian: 'Subito. Ecco a lei.', bangla: 'অবশ্যই। এই নিন আপনার জন্য।' },
      { speaker: 'Marco', italian: 'Grazie, quanto costa?', bangla: 'ধন্যবাদ, এটার দাম কত?' },
      { speaker: 'Barista', italian: 'Due euro e cinquanta.', bangla: 'দুই ইউরো পঞ্চাশ সেন্ট।' },
    ]
  },
  {
    id: 'c2',
    title: 'In un ristorante',
    banglaTitle: 'রেস্টুরেন্টে',
    icon: '🍽️',
    dialogue: [
      { speaker: 'Cameriere', italian: 'Buonasera, un tavolo per due?', bangla: 'শুভ সন্ধ্যা, দুইজনের জন্য টেবিল?' },
      { speaker: 'Cliente', italian: 'Sì, grazie. Possiamo vedere il menù?', bangla: 'হ্যাঁ, ধন্যবাদ। আমরা কি মেনু দেখতে পারি?' },
      { speaker: 'Cameriere', italian: 'Certamente, ecco a voi.', bangla: 'অবশ্যই, এই নিন আপনাদের জন্য।' },
      { speaker: 'Cliente', italian: 'Cosa consigliate oggi?', bangla: 'আজ আপনারা কী সাজেস্ট করবেন?' },
      { speaker: 'Cameriere', italian: 'La lasagna è ottima oggi.', bangla: 'আজকের লাসানিয়া খুব ভালো।' },
      { speaker: 'Cliente', italian: 'Perfetto, due lasagne e acqua.', bangla: 'চমৎকার, দুইটা লাসানিয়া এবং পানি।' },
    ]
  },
  {
    id: 'c3',
    title: 'Chiedere indicazioni',
    banglaTitle: 'পথ জিজ্ঞাসা করা',
    icon: '🗺️',
    dialogue: [
      { speaker: 'Turista', italian: 'Scusi, sa dov\'è la stazione?', bangla: 'মাফ করবেন, স্টেশন কোথায় আপনি জানেন?' },
      { speaker: 'Passante', italian: 'Sì, vada dritto per duecento metri.', bangla: 'হ্যাঁ, দুইশ মিটার সোজা যান।' },
      { speaker: 'Turista', italian: 'È lontano da qui?', bangla: 'এটা কি এখান থেকে দূরে?' },
      { speaker: 'Passante', italian: 'No, è a cinque minuti a piedi.', bangla: 'না, পায়ে হেঁটে পাঁচ মিনিট লাগবে।' },
      { speaker: 'Turista', italian: 'Grazie mille!', bangla: 'অনেক ধন্যবাদ!' },
      { speaker: 'Passante', italian: 'Prego, arrivederci.', bangla: 'স্বাগতম, বিদায়।' },
    ]
  },
  {
    id: 'c4',
    title: 'Alla stazione',
    banglaTitle: 'স্টেশনে',
    icon: '🚆',
    dialogue: [
      { speaker: 'Passeggero', italian: 'Vorrei un biglietto per Roma.', bangla: 'আমি রোমের জন্য একটি টিকিট চাই।' },
      { speaker: 'Biglietteria', italian: 'Solo andata o andata e ritorno?', bangla: 'শুধু যাওয়ার নাকি যাওয়া-আসার?' },
      { speaker: 'Passeggero', italian: 'Solo andata, grazie.', bangla: 'শুধু যাওয়ার জন্য, ধন্যবাদ।' },
      { speaker: 'Biglietteria', italian: 'Sono trenta euro. Il treno parte al binario 4.', bangla: 'ত্রিশ ইউরো হবে। ট্রেন ৪ নম্বর প্ল্যাটফর্ম থেকে ছাড়বে।' },
      { speaker: 'Passeggero', italian: 'A che ora parte?', bangla: 'কয়টার সময় ছাড়বে?' },
      { speaker: 'Biglietteria', italian: 'Parte alle dieci e mezza.', bangla: 'দশটা ত্রিশে ছাড়বে।' },
    ]
  },
  {
    id: 'c5',
    title: 'In aeroporto',
    banglaTitle: 'বিমানবন্দরে',
    icon: '✈️',
    dialogue: [
      { speaker: 'Hostess', italian: 'Buongiorno, passaporto e biglietto per favore.', bangla: 'শুভ সকাল, দয়া করে পাসপোর্ট এবং টিকিট দিন।' },
      { speaker: 'Viaggiatore', italian: 'Ecco qui.', bangla: 'এই যে নিন।' },
      { speaker: 'Hostess', italian: 'Ha bagagli da imbarcare?', bangla: 'আপনার কি চেক-ইন করার জন্য কোনো ব্যাগ আছে?' },
      { speaker: 'Viaggiatore', italian: 'Sì, solo questa valigia.', bangla: 'হ্যাঁ, শুধু এই সুটকেসটি।' },
      { speaker: 'Hostess', italian: 'Ecco la sua carta d\'imbarco.', bangla: 'এই যে আপনার বোর্ডিং কার্ড।' },
      { speaker: 'Viaggiatore', italian: 'Grazie, buona giornata.', bangla: 'ধন্যবাদ, দিনটি শুভ হোক।' },
    ]
  },
  {
    id: 'c6',
    title: 'Fare la spesa',
    banglaTitle: 'বাজার করা',
    icon: '🛒',
    dialogue: [
      { speaker: 'Cliente', italian: 'Quanto costano queste mele?', bangla: 'এই আপেলগুলোর দাম কত?' },
      { speaker: 'Venditore', italian: 'Due euro al chilo.', bangla: 'প্রতি কেজি দুই ইউরো।' },
      { speaker: 'Cliente', italian: 'Ne vorrei due chili, per favore.', bangla: 'দয়া করে আমাকে দুই কেজি দিন।' },
      { speaker: 'Venditore', italian: 'Desidera altro?', bangla: 'আর কিছু লাগবে?' },
      { speaker: 'Cliente', italian: 'Sì, un litro di latte e del pane.', bangla: 'হ্যাঁ, এক লিটার দুধ এবং কিছু রুটি।' },
      { speaker: 'Venditore', italian: 'Ecco a lei. In tutto sono sei euro.', bangla: 'এই নিন। সব মিলিয়ে ছয় ইউরো।' },
    ]
  },
  {
    id: 'c7',
    title: 'Comprare vestiti',
    banglaTitle: 'জামাকাপড় কেনা',
    icon: '👗',
    dialogue: [
      { speaker: 'Commessa', italian: 'Posso aiutarla?', bangla: 'আমি কি আপনাকে সাহায্য করতে পারি?' },
      { speaker: 'Cliente', italian: 'Cerco una maglia azzurra.', bangla: 'আমি একটি আকাশি নীল শার্ট খুঁজছি।' },
      { speaker: 'Commessa', italian: 'Che taglia porta?', bangla: 'আপনার সাইজ কত?' },
      { speaker: 'Cliente', italian: 'Porto la media. Posso provarla?', bangla: 'আমি মিডিয়াম পরি। আমি কি এটা ট্রাই করতে পারি?' },
      { speaker: 'Commessa', italian: 'Certamente, i camerini sono lì.', bangla: 'অবশ্যই, ট্রায়াল রুম ওখানে।' },
      { speaker: 'Cliente', italian: 'Mi sta bene, la prendo.', bangla: 'এটা আমার গায়ে ঠিক হয়েছে, আমি এটা নেব।' },
    ]
  },
  {
    id: 'c8',
    title: 'In farmacia',
    banglaTitle: 'ফার্মেসিতে',
    icon: '💊',
    dialogue: [
      { speaker: 'Cliente', italian: 'Buongiorno, ho un forte mal di testa.', bangla: 'শুভ সকাল, আমার খুব মাথা ব্যথা করছে।' },
      { speaker: 'Farmacista', italian: 'Ha anche la febbre?', bangla: 'আপনার কি জ্বরও আছে?' },
      { speaker: 'Cliente', italian: 'No, solo mal di testa.', bangla: 'না, শুধু মাথা ব্যথা।' },
      { speaker: 'Farmacista', italian: 'Prenda questa aspirina, una ogni otto ore.', bangla: 'এই এসপিরিনটি নিন, প্রতি আট ঘণ্টা অন্তর একটি করে।' },
      { speaker: 'Cliente', italian: 'Grazie, quanto costa?', bangla: 'ধন্যবাদ, এটার দাম কত?' },
      { speaker: 'Farmacista', italian: 'Costa cinque euro.', bangla: 'পাঁচ ইউরো।' },
    ]
  },
  {
    id: 'c9',
    title: 'Dal medico',
    banglaTitle: 'ডাক্তারের কাছে',
    icon: '👨‍⚕️',
    dialogue: [
      { speaker: 'Medico', italian: 'Cosa si sente?', bangla: 'আপনার কেমন বোধ হচ্ছে?' },
      { speaker: 'Paziente', italian: 'Mi fa male la gola e tossisco.', bangla: 'আমার গলা ব্যথা করছে এবং কাশি হচ্ছে।' },
      { speaker: 'Medico', italian: 'Da quanto tempo?', bangla: 'কতদিন ধরে?' },
      { speaker: 'Paziente', italian: 'Da due giorni.', bangla: 'দুইদিন ধরে।' },
      { speaker: 'Medico', italian: 'Le prescrivo un antibiotico.', bangla: 'আমি আপনাকে একটি অ্যান্টিবায়োটিক লিখে দিচ্ছি।' },
      { speaker: 'Paziente', italian: 'Grazie, dottore.', bangla: 'ধন্যবাদ, ডাক্তার।' },
    ]
  },
  {
    id: 'c10',
    title: 'Presentarsi',
    banglaTitle: 'পরিচয় দেওয়া',
    icon: '🤝',
    dialogue: [
      { speaker: 'Luca', italian: 'Ciao, io sono Luca. E tu?', bangla: 'হ্যালো, আমি লুকা। আর তুমি?' },
      { speaker: 'Sara', italian: 'Piacere, io sono Sara.', bangla: 'শুভেচ্ছা, আমি সারা।' },
      { speaker: 'Luca', italian: 'Di dove sei, Sara?', bangla: 'সারা, তুমি কোথা থেকে এসেছ?' },
      { speaker: 'Sara', italian: 'Sono di Milano, ma vivo a Roma.', bangla: 'আমি মিলান থেকে এসেছি, কিন্তু রোমে থাকি।' },
      { speaker: 'Luca', italian: 'Quanti anni hai?', bangla: 'তোমার বয়স কত?' },
      { speaker: 'Sara', italian: 'Ho venticinque anni.', bangla: 'আমার বয়স পঁচিশ বছর।' },
    ]
  },
  {
    id: 'c11',
    title: 'Al telefono',
    banglaTitle: 'ফোনে কথা বলা',
    icon: '📱',
    dialogue: [
      { speaker: 'Pronto', italian: 'Pronto, chi parla?', bangla: 'হ্যালো, কে বলছেন?' },
      { speaker: 'Chiamante', italian: 'Ciao, sono Maria. C\'è Paolo?', bangla: 'হ্যালো, আমি মারিয়া। পাওলো কি আছে?' },
      { speaker: 'Pronto', italian: 'Sì, te lo passo subito.', bangla: 'হ্যাঁ, আমি তাকে এখনই দিচ্ছি।' },
      { speaker: 'Paolo', italian: 'Ciao Maria, come stai?', bangla: 'হ্যালো মারিয়া, কেমন আছ?' },
      { speaker: 'Maria', italian: 'Bene, ti andrebbe di uscire stasera?', bangla: 'ভালো, তুমি কি আজ সন্ধ্যায় বাইরে বের হতে চাও?' },
      { speaker: 'Paolo', italian: 'Certo, a che ora?', bangla: 'অবশ্যই, কয়টায়?' },
    ]
  },
  {
    id: 'c12',
    title: 'Prenotare un hotel',
    banglaTitle: 'হোটেল বুক করা',
    icon: '🏨',
    dialogue: [
      { speaker: 'Reception', italian: 'Hotel Minerva, buongiorno.', bangla: 'হোটেল মিনার্ভা, শুভ সকাল।' },
      { speaker: 'Cliente', italian: 'Buongiorno, vorrei prenotare una stanza.', bangla: 'শুভ সকাল, আমি একটি রুম বুক করতে চাই।' },
      { speaker: 'Reception', italian: 'Per quante notti?', bangla: 'কয়টি রাতের জন্য?' },
      { speaker: 'Cliente', italian: 'Per tre notti, dal lunedì al giovedì.', bangla: 'তিন রাতের জন্য, সোমবার থেকে বৃহস্পতিবার।' },
      { speaker: 'Reception', italian: 'Singola o doppia?', bangla: 'সিঙ্গেল নাকি ডাবল?' },
      { speaker: 'Cliente', italian: 'Una doppia, grazie.', bangla: 'একটি ডাবল রুম, ধন্যবাদ।' },
    ]
  },
  {
    id: 'c13',
    title: 'Al mercato',
    banglaTitle: 'বাজারে',
    icon: '🍅',
    dialogue: [
      { speaker: 'Venditore', italian: 'Oggi abbiamo pomodori freschi!', bangla: 'আজ আমাদের কাছে টাটকা টমেটো আছে!' },
      { speaker: 'Cliente', italian: 'Quanto costa un chilo?', bangla: 'এক কেজির দাম কত?' },
      { speaker: 'Venditore', italian: 'Solo un euro e cinquanta.', bangla: 'মাত্র এক ইউরো পঞ্চাশ সেন্ট।' },
      { speaker: 'Cliente', italian: 'Me ne dia due chili, per favore.', bangla: 'দয়া করে আমাকে দুই কেজি দিন।' },
      { speaker: 'Venditore', italian: 'Altro? Abbiamo anche dell\'uva.', bangla: 'আর কিছু? আমাদের কাছে আঙুরও আছে।' },
      { speaker: 'Cliente', italian: 'No, basta così. Grazie.', bangla: 'না, এটুকুই যথেষ্ট। ধন্যবাদ।' },
    ]
  },
  {
    id: 'c14',
    title: 'In ufficio postale',
    banglaTitle: 'পোস্ট অফিসে',
    icon: '✉️',
    dialogue: [
      { speaker: 'Cliente', italian: 'Vorrei spedire questa lettera.', bangla: 'আমি এই চিঠিটি পাঠাতে চাই।' },
      { speaker: 'Impiegato', italian: 'Per dove?', bangla: 'কোথায়?' },
      { speaker: 'Cliente', italian: 'Per il Bangladesh.', bangla: 'বাংলাদেশে।' },
      { speaker: 'Impiegato', italian: 'Deve essere raccomandata?', bangla: 'এটা কি রেজিস্ট্রি করে পাঠাতে হবে?' },
      { speaker: 'Cliente', italian: 'Sì, per favore.', bangla: 'হ্যাঁ, দয়া করে।' },
      { speaker: 'Impiegato', italian: 'Sono otto euro in totale.', bangla: 'সব মিলিয়ে আট ইউরো হবে।' },
    ]
  },
  {
    id: 'c15',
    title: 'In banca',
    banglaTitle: 'ব্যাংকে',
    icon: '🏦',
    dialogue: [
      { speaker: 'Cliente', italian: 'Buongiorno, vorrei aprire un conto.', bangla: 'শুভ সকাল, আমি একটি অ্যাকাউন্ট খুলতে চাই।' },
      { speaker: 'Impiegato', italian: 'Certamente. Mi dà un documento?', bangla: 'অবশ্যই। আমাকে একটি পরিচয়পত্র দেবেন?' },
      { speaker: 'Cliente', italian: 'Ecco la mia carta d\'identità.', bangla: 'এই নিন আমার আইডি কার্ড।' },
      { speaker: 'Impiegato', italian: 'Deve compilare questo modulo.', bangla: 'আপনাকে এই ফর্মটি পূরণ করতে হবে।' },
      { speaker: 'Cliente', italian: 'Posso prelevare dei soldi ora?', bangla: 'আমি কি এখন কিছু টাকা তুলতে পারি?' },
      { speaker: 'Impiegato', italian: 'Tra un attimo, appena finito.', bangla: 'এক মুহূর্ত, কাজ শেষ হলেই পারবেন।' },
    ]
  },
  {
    id: 'c16',
    title: 'Dal parrucchiere',
    banglaTitle: 'সেলুনে',
    icon: '💇‍♂️',
    dialogue: [
      { speaker: 'Parrucchiere', italian: 'Come desidera i capelli oggi?', bangla: 'আজ আপনি চুল কেমন কাটতে চান?' },
      { speaker: 'Cliente', italian: 'Solo una spuntatina, grazie.', bangla: 'শুধু একটু ছেঁটে দিন, ধন্যবাদ।' },
      { speaker: 'Parrucchiere', italian: 'Vuole anche lo shampoo?', bangla: 'আপনি কি শ্যাম্পুও করতে চান?' },
      { speaker: 'Cliente', italian: 'Sì, volentieri.', bangla: 'হ্যাঁ, সানন্দে।' },
      { speaker: 'Parrucchiere', italian: 'Preferisce il gel o la lacca?', bangla: 'আপনি কি জেল নাকি হেয়ার স্প্রে পছন্দ করবেন?' },
      { speaker: 'Cliente', italian: 'Un po\' di gel va bene.', bangla: 'একটু জেল দিলেই হবে।' },
    ]
  },
  {
    id: 'c17',
    title: 'In biblioteca',
    banglaTitle: 'লাইব্রেরিতে',
    icon: '📖',
    dialogue: [
      { speaker: 'Studente', italian: 'Cerco un libro di storia italiana.', bangla: 'আমি ইতালীয় ইতিহাসের একটি বই খুঁজছি।' },
      { speaker: 'Bibliotecaria', italian: 'Sono nella sezione C, scaffale 4.', bangla: 'সেগুলো সেকশন সি, ৪ নম্বর তাকে আছে।' },
      { speaker: 'Studente', italian: 'Posso prenderlo in prestito?', bangla: 'আমি কি এটা ধার নিতে পারি?' },
      { speaker: 'Bibliotecaria', italian: 'Sì, per due settimane.', bangla: 'হ্যাঁ, দুই সপ্তাহের জন্য।' },
      { speaker: 'Studente', italian: 'Ho bisogno della tessera?', bangla: 'আমার কি লাইব্রেরি কার্ড লাগবে?' },
      { speaker: 'Bibliotecaria', italian: 'Sì, per favore.', bangla: 'হ্যাঁ, দয়া করে।' },
    ]
  },
  {
    id: 'c18',
    title: 'Chiedere l\'ora',
    banglaTitle: 'সময় জিজ্ঞাসা করা',
    icon: '⌚',
    dialogue: [
      { speaker: 'A', italian: 'Scusi, ha l\'ora?', bangla: 'মাফ করবেন, আপনার কাছে সময় আছে?' },
      { speaker: 'B', italian: 'Sì, sono le tre e un quarto.', bangla: 'হ্যাঁ, এখন তিনটা বেজে পনেরো মিনিট।' },
      { speaker: 'A', italian: 'Il mio orologio è fermo.', bangla: 'আমার ঘড়ি বন্ধ হয়ে গেছে।' },
      { speaker: 'B', italian: 'Nessun problema. Ha fretta?', bangla: 'কোনো সমস্যা নেই। আপনার কি তাড়া আছে?' },
      { speaker: 'A', italian: 'Sì, ho un appuntamento alle quattro.', bangla: 'হ্যাঁ, চারটার সময় আমার একটি অ্যাপয়েন্টমেন্ট আছে।' },
      { speaker: 'B', italian: 'Allora faccia presto!', bangla: 'তাহলে তাড়াতাড়ি করুন!' },
    ]
  },
  {
    id: 'c19',
    title: 'Il meteo',
    banglaTitle: 'আবহাওয়া',
    icon: '☀️',
    dialogue: [
      { speaker: 'A', italian: 'Che bel sole oggi, vero?', bangla: 'আজ কী সুন্দর রোদ, তাই না?' },
      { speaker: 'B', italian: 'Sì, fa molto caldo.', bangla: 'হ্যাঁ, অনেক গরম।' },
      { speaker: 'A', italian: 'Dicono che domani pioverà.', bangla: 'তারা বলছে আগামীকাল বৃষ্টি হবে।' },
      { speaker: 'B', italian: 'Speriamo di no, devo andare al mare.', bangla: 'আশা করি হবে না, আমাকে সমুদ্র সৈকতে যেতে হবে।' },
      { speaker: 'A', italian: 'Porta comunque l\'ombrello.', bangla: 'তবুও ছাতা সাথে রেখো।' },
      { speaker: 'B', italian: 'Hai ragione, meglio essere prudenti.', bangla: 'তুমি ঠিক বলেছ, সতর্ক থাকা ভালো।' },
    ]
  },
  {
    id: 'c20',
    title: 'Hobby e sport',
    banglaTitle: 'শখ ও খেলাধুলা',
    icon: '⚽',
    dialogue: [
      { speaker: 'A', italian: 'Cosa fai nel tempo libero?', bangla: 'অবসর সময়ে তুমি কী করো?' },
      { speaker: 'B', italian: 'Mi piace molto giocare a calcio.', bangla: 'আমি ফুটবল খেলতে খুব পছন্দ করি।' },
      { speaker: 'A', italian: 'Sei tifoso di qualche squadra?', bangla: 'তুমি কি কোনো দলের সমর্থক?' },
      { speaker: 'B', italian: 'Sì, tifo per la Juventus.', bangla: 'হ্যাঁ, আমি জুভেন্টাসের সমর্থক।' },
      { speaker: 'A', italian: 'A me invece piace il cinema.', bangla: 'অন্যদিকে আমি সিনেমা পছন্দ করি।' },
      { speaker: 'B', italian: 'Che tipo di film preferisci?', bangla: 'তুমি কোন ধরনের সিনেমা পছন্দ করো?' },
    ]
  },
  {
    id: 'c21',
    title: 'Famiglia',
    banglaTitle: 'পরিবার',
    icon: '👨‍👩-👧‍👦',
    dialogue: [
      { speaker: 'A', italian: 'Hai fratelli o sorelle?', bangla: 'তোমার কি ভাই বা বোন আছে?' },
      { speaker: 'B', italian: 'Ho un fratello maggiore e una sorella minore.', bangla: 'আমার এক বড় ভাই এবং এক ছোট বোন আছে।' },
      { speaker: 'A', italian: 'Tua sorella vive ancora con i tuoi?', bangla: 'তোমার বোন কি এখনও তোমার বাবা-মায়ের সাথে থাকে?' },
      { speaker: 'B', italian: 'Sì, lei studia ancora.', bangla: 'হ্যাঁ, সে এখনও পড়াশোনা করছে।' },
      { speaker: 'A', italian: 'E i tuoi genitori cosa fanno?', bangla: 'আর তোমার বাবা-মা কী করেন?' },
      { speaker: 'B', italian: 'Mio padre è medico e mia madre è insegnante.', bangla: 'আমার বাবা ডাক্তার এবং মা শিক্ষক।' },
    ]
  },
  {
    id: 'c22',
    title: 'Studio',
    banglaTitle: 'পড়াশোনা',
    icon: '🎓',
    dialogue: [
      { speaker: 'A', italian: 'Cosa studi all\'università?', bangla: 'তুমি ইউনিভার্সিটিতে কী পড়ো?' },
      { speaker: 'B', italian: 'Studio ingegneria informatica.', bangla: 'আমি কম্পিউটার ইঞ্জিনিয়ারিং পড়ছি।' },
      { speaker: 'A', italian: 'È difficile come dicono?', bangla: 'এটা কি লোকে যেমন বলে তেমন কঠিন?' },
      { speaker: 'B', italian: 'Sì, ci sono molti esami pesanti.', bangla: 'হ্যাঁ, অনেকগুলো কঠিন পরীক্ষা আছে।' },
      { speaker: 'A', italian: 'Quando ti laurei?', bangla: 'তোমার গ্র্যাজুয়েশন কবে শেষ হবে?' },
      { speaker: 'B', italian: 'Spero l\'anno prossimo.', bangla: 'আশা করি আগামী বছর।' },
    ]
  },
  {
    id: 'c23',
    title: 'Lavoro',
    banglaTitle: 'কাজ / চাকরি',
    icon: '💼',
    dialogue: [
      { speaker: 'A', italian: 'Dove lavori?', bangla: 'তুমি কোথায় কাজ করো?' },
      { speaker: 'B', italian: 'Lavoro in una banca in centro.', bangla: 'আমি শহরের কেন্দ্রে একটি ব্যাংকে কাজ করি।' },
      { speaker: 'A', italian: 'Ti piace il tuo lavoro?', bangla: 'তুমি কি তোমার কাজ পছন্দ করো?' },
      { speaker: 'B', italian: 'Sì, ma è molto stressante.', bangla: 'হ্যাঁ, কিন্তু এটি খুব চাপের।' },
      { speaker: 'A', italian: 'A che ora finisci di solito?', bangla: 'সাধারণত কয়টায় তুমি কাজ শেষ করো?' },
      { speaker: 'B', italian: 'Alle sei del pomeriggio.', bangla: 'বিকেল ছয়টায়।' },
    ]
  },
  {
    id: 'c24',
    title: 'Al cinema',
    banglaTitle: 'সিনেমায়',
    icon: '🎬',
    dialogue: [
      { speaker: 'A', italian: 'Andiamo al cinema stasera?', bangla: 'আমরা কি আজ রাতে সিনেমা দেখতে যাব?' },
      { speaker: 'B', italian: 'Cosa fanno di bello?', bangla: 'কী ভালো সিনেমা চলছে?' },
      { speaker: 'A', italian: 'C\'è il nuovo film di fantascienza.', bangla: 'নতুন একটি সায়েন্স ফিকশন সিনেমা এসেছে।' },
      { speaker: 'B', italian: 'D’accordo, prendo io i biglietti.', bangla: 'ঠিক আছে, আমি টিকিট কাটছি।' },
      { speaker: 'A', italian: 'Vuoi dei popcorn?', bangla: 'তুমি কি পপকর্ন নেবে?' },
      { speaker: 'B', italian: 'Sì, e anche una coca grande.', bangla: 'হ্যাঁ, এবং সাথে একটি বড় কোকও।' },
    ]
  },
  {
    id: 'c25',
    title: 'In pizzeria',
    banglaTitle: 'পিজ্জারিয়াতে',
    icon: '🍕',
    dialogue: [
      { speaker: 'A', italian: 'Una pizza Margherita e una birra, per favore.', bangla: 'দয়া করে একটি মার্গারিটা পিজ্জা এবং একটি বিয়ার দিন।' },
      { speaker: 'Cameriere', italian: 'Sottile o alta?', bangla: 'পাতলা নাকি মোটা ক্রাস্ট?' },
      { speaker: 'A', italian: 'Sottile, grazie.', bangla: 'পাতলা, ধন্যবাদ।' },
      { speaker: 'Cameriere', italian: 'Altro?', bangla: 'আর কিছু?' },
      { speaker: 'A', italian: 'No, grazie. Il conto subito, per favore.', bangla: 'না, ধন্যবাদ। দয়া করে এখনই বিলটা দিন।' },
      { speaker: 'Cameriere', italian: 'Subito. Sono dodici euro.', bangla: 'অবশ্যই। বারো ইউরো হবে।' },
    ]
  },
  {
    id: 'c26',
    title: 'Taxi',
    banglaTitle: 'ট্যাক্সি',
    icon: '🚕',
    dialogue: [
      { speaker: 'Passeggero', italian: 'Mi porti in Piazza Navona, per favore.', bangla: 'দয়া করে আমাকে পিয়াজ্জা নাভোনায় নিয়ে চলুন।' },
      { speaker: 'Tassista', italian: 'C\'è molto traffico oggi.', bangla: 'আজ অনেক জ্যাম আছে।' },
      { speaker: 'Passeggero', italian: 'Ci vorrà molto tempo?', bangla: 'অনেক সময় লাগবে কি?' },
      { speaker: 'Tassista', italian: 'Circa venti minuti.', bangla: 'প্রায় বিশ মিনিট।' },
      { speaker: 'Passeggero', italian: 'Quanto le devo?', bangla: 'কত ভাড়া হয়েছে?' },
      { speaker: 'Tassista', italian: 'Sono quindici euro.', bangla: 'পনেরো ইউরো হবে।' },
    ]
  },
  {
    id: 'c27',
    title: 'Al distributore',
    banglaTitle: 'গ্যাস স্টেশনে',
    icon: '⛽',
    dialogue: [
      { speaker: 'A', italian: 'Faccia il pieno di benzina, per favore.', bangla: 'দয়া করে ফুল ট্যাঙ্ক তেল দিন।' },
      { speaker: 'Addetto', italian: 'Senza piombo o diesel?', bangla: 'আনলেডেড পেট্রোল নাকি ডিজেল?' },
      { speaker: 'A', italian: 'Senza piombo.', bangla: 'আনলেডেড পেট্রোল।' },
      { speaker: 'Addetto', italian: 'Vuole anche controllare l\'olio?', bangla: 'আপনি কি ইঞ্জিন অয়েলও চেক করতে চান?' },
      { speaker: 'A', italian: 'No, va bene così.', bangla: 'না, এভাবেই হবে।' },
      { speaker: 'Addetto', italian: 'Sono ottanta euro.', bangla: 'আশি ইউরো হবে।' },
    ]
  },
  {
    id: 'c28',
    title: 'Al museo',
    banglaTitle: 'মিউজিয়ামে',
    icon: '🖼️',
    dialogue: [
      { speaker: 'Visitatore', italian: 'A che ora chiude il museo?', bangla: 'মিউজিয়াম কয়টায় বন্ধ হয়?' },
      { speaker: 'Guida', italian: 'Chiude alle sette di sera.', bangla: 'বিকেল সাতটায় বন্ধ হয়।' },
      { speaker: 'Visitatore', italian: 'Posso fare delle foto?', bangla: 'আমি কি ছবি তুলতে পারি?' },
      { speaker: 'Guida', italian: 'Sì, ma senza flash.', bangla: 'হ্যাঁ, তবে ফ্ল্যাশ ছাড়া।' },
      { speaker: 'Visitatore', italian: 'Dov\'è la stanza di Leonardo?', bangla: 'লিওনার্দোর রুমটি কোথায়?' },
      { speaker: 'Guida', italian: 'Al secondo piano, a sinistra.', bangla: 'দ্বিতীয় তলায়, বাম দিকে।' },
    ]
  },
  {
    id: 'c29',
    title: 'Al parco',
    banglaTitle: 'পার্কে',
    icon: '🌳',
    dialogue: [
      { speaker: 'A', italian: 'Facciamo una passeggiata?', bangla: 'আমরা কি একটু হাঁটতে যাব?' },
      { speaker: 'B', italian: 'Sì, andiamo al parco.', bangla: 'হ্যাঁ, চলো পার্কে যাই।' },
      { speaker: 'A', italian: 'Ci sono molti fiori bellissimi.', bangla: 'এখানে অনেকগুলো সুন্দর ফুল আছে।' },
      { speaker: 'B', italian: 'Guarda quell\'albero grande.', bangla: 'ওই বড় গাছটি দেখো।' },
      { speaker: 'A', italian: 'Ci sediamo su quella panchina?', bangla: 'আমরা কি ওই বেঞ্চটিতে বসব?' },
      { speaker: 'B', italian: 'Sì, si sta molto bene qui.', bangla: 'হ্যাঁ, এখানে খুব আরাম লাগছে।' },
    ]
  },
  {
    id: 'c30',
    title: 'Emergenza',
    banglaTitle: 'জরুরি অবস্থা',
    icon: '🆘',
    dialogue: [
      { speaker: 'A', italian: 'Aiuto! Qualcuno mi aiuti!', bangla: 'বাঁচাও! কেউ আমাকে সাহায্য করুন!' },
      { speaker: 'B', italian: 'Cosa è successo?', bangla: 'কী হয়েছে?' },
      { speaker: 'A', italian: 'Mi hanno rubato la borsa!', bangla: 'আমার ব্যাগ চুরি হয়েছে!' },
      { speaker: 'B', italian: 'Chiamo subito la polizia.', bangla: 'আমি এখনই পুলিশকে ফোন দিচ্ছি।' },
      { speaker: 'A', italian: 'Grazie, sono molto spaventata.', bangla: 'ধন্যবাদ, আমি খুব ভয় পেয়েছি।' },
      { speaker: 'B', italian: 'Stia calma, sta arrivando qualcuno.', bangla: 'শান্ত হোন, কেউ একজন আসছে।' },
    ]
  }
];

export const LESSONS: Lesson[] = [
  {
    id: 'l0',
    title: "L'Alfabeto Italiano",
    banglaTitle: 'বর্ণমালা',
    description: 'Learn the Italian alphabet with pronunciation.',
    level: DifficultyLevel.ALPHABET,
    icon: '✨',
    content: ALPHABET_DATA
  },
  {
    id: 'l1',
    title: 'Saluti',
    banglaTitle: 'অভিবাদন',
    description: 'Basic greetings and pleasantries.',
    level: DifficultyLevel.BEGINNER,
    icon: '👋',
    content: [
      { id: 's1', italian: 'Ciao', bangla: 'হ্যালো / বিদায়' },
      { id: 's2', italian: 'Buongiorno', bangla: 'শুভ সকাল' },
      { id: 's3', italian: 'Buonasera', bangla: 'শুভ সন্ধ্যা' },
      { id: 's4', italian: 'Buonanotte', bangla: 'শুভ রাত্রি' },
      { id: 's5', italian: 'Come stai?', bangla: 'তুমি কেমন আছো?' },
    ]
  },
  {
    id: 'l1b',
    title: 'Saluti e Basi',
    banglaTitle: 'অভিবাদন ও সাধারণ শব্দ',
    description: '100 essential greetings and basic phrases.',
    level: DifficultyLevel.BEGINNER,
    icon: '🤝',
    content: GREETINGS_100
  },
  {
    id: 'l2',
    title: 'Verbi Fondamentali',
    banglaTitle: 'মৌলিক ক্রিয়াপদসমূহ',
    description: '100 of the most important Italian verbs.',
    level: DifficultyLevel.BEGINNER,
    icon: '⚡',
    content: VERBS_100
  }
];
